version: '3.7'

services:
  localstack:
      image: localstack/localstack:0.11.2
      container_name: localstack
      environment:
          - SERVICES=sqs,sns
          - DEFAULT_REGION=us-east-1
          - DATA_DIR=/tmp/localstack/data
      ports:
          - 4566:4566
          - 8085:8080
      volumes:
          - test:/tmp/test

volumes:
  test:
    name: test